-- MySQL Script generated by MySQL Workbench
-- Wed Feb  5 20:11:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LinkMe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LinkMe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LinkMe` DEFAULT CHARACTER SET utf8 ;
USE `LinkMe` ;

-- -----------------------------------------------------
-- Table `LinkMe`.`CREDENTIALS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LinkMe`.`CREDENTIALS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(32) NOT NULL,
  `PASSWORD` BLOB(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LinkMe`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LinkMe`.`USERS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `CREDENTIALS_ID` INT NOT NULL,
  `FIRSTNAME` VARCHAR(32) NOT NULL,
  `LASTNAME` VARCHAR(32) NOT NULL,
  `EMAIL` VARCHAR(128) NOT NULL,
  `CITY` VARCHAR(32) NOT NULL,
  `STATE` VARCHAR(2) NOT NULL,
  `SUSPENDED` TINYINT NOT NULL DEFAULT 0,
  `BIRTHDAY` DATE NULL,
  `TAGLINE` VARCHAR(255) NULL,
  `PHOTO` VARCHAR(128) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_USERS_CREDENTIALS_idx` (`CREDENTIALS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_USERS_CREDENTIALS`
    FOREIGN KEY (`CREDENTIALS_ID`)
    REFERENCES `LinkMe`.`CREDENTIALS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LinkMe`.`ADMINS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LinkMe`.`ADMINS` (
  `USERS_ID` INT NOT NULL,
  INDEX `fk_table1_USERS1_idx` (`USERS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_table1_USERS1`
    FOREIGN KEY (`USERS_ID`)
    REFERENCES `LinkMe`.`CREDENTIALS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LinkMe`.`PASTJOBS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LinkMe`.`PASTJOBS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `COMPANY` VARCHAR(128) NOT NULL,
  `JOBTITLE` VARCHAR(128) NOT NULL,
  `DESCRIPTION` VARCHAR(255) NULL,
  `USERS_ID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PASTJOBS_USERS1_idx` (`USERS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PASTJOBS_USERS1`
    FOREIGN KEY (`USERS_ID`)
    REFERENCES `LinkMe`.`CREDENTIALS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
